### ISSUE TITLE
Need help on calculating optical strain

### ISSUE THREAD

**Issue by gibbsbupt** [IcedDoggie/Micro-Expression-with-Deep-Learning#26]
We found some unclear points in the script _output_strain.m_ in the External-Tools folder.  In line 103 `[opticalStrain, strain_orientation, exx, eyy] = os(output)`, there's a function called "os" but we can't find a script named os or the definition of the function. Could you please upload the code of the function os mentioned above ? Looking forward to your reply, thanks.

**Comment by zskadazhang** [comment]
I am sorry for that i can not help you ,could you please tell me how to use TIM?

**Comment by xiaoroulian** [comment]
> I am sorry for that i can not help you ,could you please tell me how to use TIM?

+1

**Comment by IcedDoggie** [comment]
Hi, 
for Strain computation, please refer https://www.sciencedirect.com/science/article/pii/S0923596517302436
for TIM, please refer: http://www.cse.oulu.fi/CMV/Downloads

**Comment by gibbsbupt** [comment]
> I am sorry for that i can not help you ,could you please tell me how to use TIM?
> 
> +1



> I am sorry for that i can not help you ,could you please tell me how to use TIM?

please refer https://github.com/zsdust/TIM-temporal-interpolation-model/blob/master/test.m
The original script is used for doubling the length of a video, so you may modify the codes in line 21 and 26 for TIM10.

**Comment by xiaoroulian** [comment]
> > I am sorry for that i can not help you ,could you please tell me how to use TIM?
> > +1
> 
> > I am sorry for that i can not help you ,could you please tell me how to use TIM?
> 
> please refer https://github.com/zsdust/TIM-temporal-interpolation-model/blob/master/test.m
> The original script is used for doubling the length of a video, so you may modify the codes in line 21 and 26 for TIM10.

Thank you for your reply. It helped me a lot.
If you don't mind, could you tell me how to modify the code?
I'm still a little confused.

**Comment by masiyuan423** [comment]
Hello, I'm sorry to bother you. I have been doing this work for some time. Have you solved the problem?Is it convenient to contact and consult?
This is my email address: masiyuan423@163.com.I hope to get your reply

**Comment by JayShaun** [comment]
> We found some unclear points in the script _output_strain.m_ in the External-Tools folder. In line 103 `[opticalStrain, strain_orientation, exx, eyy] = os(output)`, there's a function called "os" but we can't find a script named os or the definition of the function. Could you please upload the code of the function os mentioned above ? Looking forward to your reply, thanks.

Have you solved the problem? Can you send me the os.m file? Thanks a lot! email: xinliangzhai@126.com

**Comment by gibbsbupt** [comment]
> We found some unclear points in the script output_strain.m in the External-Tools folder. In line 103 [opticalStrain, strain_orientation, exx, eyy] = os(output), there's a function called "os" but we can't find a script named os or the definition of the function. Could you please upload the code of the function os mentioned above ? Looking forward to your reply, thanks.
> 
> Have you solved the problem? Can you send me the os.m file? Thanks a lot! email: xinliangzhai@126.com

Nope. We only use optical flow instead.

**Comment by liushaowei123** [comment]
> 
> 
> Hi,
> for Strain computation, please refer https://www.sciencedirect.com/science/article/pii/S0923596517302436
> for TIM, please refer: http://www.cse.oulu.fi/CMV/Downloads

I don't konw how to code the calculating optical strain , can you send me the os.m file?  Thank you very much,  my email is 1262966556@qq.com

**Comment by gibbsbupt** [comment]
> Hi,
> for Strain computation, please refer https://www.sciencedirect.com/science/article/pii/S0923596517302436
> for TIM, please refer: http://www.cse.oulu.fi/CMV/Downloads
> 
> I don't konw how to code the calculating optical strain , can you send me the os.m file?  Thank you very much,  my email is 1262966556@qq.com

The issue was also opened to request the document from the author, but the author only provided some references. So we gave up the use of optical strain and only used optical flow. Btw, we are no longer working on this project, sorry.
