### ISSUE TITLE
Use of TIM

### ISSUE THREAD

**Issue by WJShengD** [IcedDoggie/Micro-Expression-with-Deep-Learning#36]
I downloaded the TIM code from the connection you gave, but there are only three. M files in it. I don't know how to use it. Can you tell me? Thank you.

**Comment by liimy1** [comment]
Hello, where did you download TIM code? Sorry, I didn't find it. Would you please send me one? Thank you very much. My email address is liimengyu@163.com.

**Comment by jstulips** [comment]
@liimy1 The original link from Oulu CMVS seems to be broken at the moment. Here's another repo: https://github.com/zsdust/TIM-temporal-interpolation-model

**Comment by liimy1** [comment]
thank you! You've done me a big favor.



At 2021-04-05 09:26:07, "jstulips" ***@***.***> wrote:

@liimy1 The original link from Oulu CMVS seems to be broken at the moment. Here's another repo: https://github.com/zsdust/TIM-temporal-interpolation-model
